[package]
name = "godotserver"
version = "0.1.0"
edition = "2021"

[dependencies]
enet={git="https://github.com/LeonMatthes/enet-rs.git", branch="moduleverse"}
serde = {version = "1.0.215", features = ["derive"]}
bincode = "1.3.3"
tokio = {version = "1.41.1", features = ["full"]}
